In [1]:
import tensorflow as tf

WARNING:tensorflow:From c:\Users\balaa\OneDrive\Documents\AI\deep_learning\model2\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [63]:
### Load the trained model, scaler pickle,onehot
model=load_model('model.h5')

## load the encoder and scaler
with open('one_hot.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)

with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

In [64]:
input_data={
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [65]:
geo_encoder=one_hot.transform([[input_data['Geography']]]).toarray()
geo_ecoder_df=pd.DataFrame(geo_encoder,columns=one_hot.get_feature_names_out(['Geography']))

c:\Users\balaa\OneDrive\Documents\AI\deep_learning\model2\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [66]:

geo_ecoder_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [67]:
input_df=pd.DataFrame([input_data])

In [68]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [69]:
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [70]:
input_data

{'CreditScore': 600,
 'Geography': 'France',
 'Gender': 'Male',
 'Age': 40,
 'Tenure': 3,
 'Balance': 60000,
 'NumOfProducts': 2,
 'HasCrCard': 1,
 'IsActiveMember': 1,
 'EstimatedSalary': 50000}

In [71]:
input_df=pd.concat([input_df.drop('Geography',axis=1 ),geo_ecoder_df],axis=1)

In [72]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [73]:
input_scaled=scaler.transform(input_df)

In [74]:
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [75]:
predicted_op=model.predict(input_scaled)
predicted_op

1/1 [==============================] - 0s 115ms/step

array([[0.05230729]], dtype=float32)

In [76]:
pb=predicted_op[0][0]
pb

0.052307293

In [80]:
if pb > 0.5:
    print("the customer is likely to churn")
else:
    print("the customer is not likely to churn")

the customer is not likely to churn